language: python
python:
    - "2.7"
install: pip install -r requirements.txt --use-mirrors
env:
    global:
        - secure: "nQvQfDl3eV4yCJ0Wj/6lne+NEt2Qbgbs+zZ2yoNYCNJEu3X/GiNdeNJAiFyt\nh70c7kTkiIOZhDu8Ay0yfXBG6Ma68ATkdYjGD/wJmcKSeTiNYs0yLV/hHg6W\nc2+ifoIpi/J3edlJ9RRfTCVDhpWUBsp3fldTmYecN0WAiKENxyc="
        - secure: "ketT9pBflKhbTLxbcalBm8Vfw4VL0XAcmSgUkrepLXGqeGoNUITNr9dBmWUK\nx5fdzaFozs5asIkHInIZiTOXbylA2XPg+PuePt0t/H50QiBGuJuoNTdHJpiS\nrpNLIWQPoAmP5/NC646SrFQdtm0vKI55in7eEEk79+AD8JHyYUk="
        - secure: "aEpfmuapg2F0wnsmNgO1hj4VL2WRkt07QHUv29RqcWS3uIXWy06oX1BVTMAL\nz4Kcm9JTQKbH4m/DzKVLLnKktMUbrmXlsmme5QpZnivyiJhGjRQ9aZkH5Agq\nhGI/L0PAM5YmjINCI/FXIzNpiO9l4p/48PQDh0uR2MSOpmgfCWg="
        - secure: "AFFy6VlL/yo+bsUdEOoKNLAcEpzTawR5IP8aY/yQI6s0e6o0mQ5W37t5tXXy\nUfqFsjG/xSFTGNJdtVsKSSV3aFR2T3KnvhqgKiQ64GTlcwxAxoS4B5XJUFS3\ndpRYV0LBFmNX/Ml+Auwk1ijV0+/iB+90XEWXJ0FaPoAZ9HcY1d0="
        - AWS_UPLOAD_BUCKET="alexandria-build-logs"
script: ./runtests.sh
after_success:
    - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
    - git remote add heroku git@heroku.com:alexandria-demo.git
    - echo "Host heroku.com" >> ~/.ssh/config
    - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
    - echo "   CheckHostIP no" >> ~/.ssh/config
    - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config 
    - heroku keys:clear
    - yes | heroku keys:add
    - yes | git push heroku master
    - heroku run python manage.py migrate --settings=emubaby.settings.heroku
    - tar -zcvf coverage-report.tar.gz htmlcov/
    - python utils/post_build.py "Build Number" $TRAVIS_BUILD_NUMBER "Branch" "$TRAVIS_BRANCH" "Commit" "$TRAVIS_COMMIT" -u upload -k $ALEXANDRIA_API_KEY --host http://alexandria-demo.herokuapp.com/ -n "Travis CI Build $TRAVIS_BUILD_NUMBER"
    - python utils/upload_artifact.py "Coverage Report" coverage-report.tar.gz (cat build_number) upload $ALEXANDRIA_API_KEY --host http://alexandria-demo.herokuapp.com/ -k $AWS_ACCESS_KEY -s $AWS_ACCESS_SECRET -b $AWS_UPLOAD_BUCKET
